---

- name: ah database
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: False
  vars:
    ansible_dest_release: "xenial"
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
  - name: Update existing packages
    apt:
      update_cache: yes

  - name: Upgrade all packages to the latest version
    apt:
      update_cache: yes

  - name: Install needed packages
    apt:
      update_cache: false
      name:
        - python3-apt
        - python3
        - python3-pip
        - postgresql
        - postgresql-contrib
      state: present

  - name: Update existing packages
    apt:
      update_cache: yes

  - name: Install psycopg2
    pip:
      name: psycopg2
      state: latest

  - name: Create postgres db
    become_user: postgres
    postgresql_db:
      name: ah

  - name: Create a new user
    become_user: postgres
    postgresql_user:
      name: dario
      password: daferario

  - name: Set priviledges
    become_user: postgres
    postgresql_privs:
      db: postgres
      priv: ALL
      type: database
      obj: ah
      role: dario
