---

- name: ah documentation
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: False
  vars:
    ansible_dest_release: "xenial"
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
  - name: Update existing packages
    apt:
      update_cache: yes

  - name: Upgrade all packages to the latest version
    apt:
      update_cache: yes

  - name: Install needed packages
    apt:
      update_cache: false
      name:
        - python3-apt
        - python3
        - python3-pip
        - python-dev
        - python-setuptools
      state: present

  - name: Install virtualenv
    pip:
      name: virtualenv
      state: latest

  - name: Clone the repository
    git:
      repo: https://github.com/andela/ah-code-titans.git
      dest: /home/ubuntu/ah-code-titans
      clone: yes

  - name: Copy environmental configurations
    copy:
      src: .app_env
      dest: /home/ubuntu/.env

  - name: create a virtual environment
    shell:
      cmd: |
        cd /home/ubuntu/
        virtualenv --python=python3 ahvenv

  - name: config file to run app in background
    copy:
      src: keep_alive.service
      dest: /lib/systemd/system/keep_alive.service

  - name: copy script to run application in the background
    copy:
      src: start_ah.sh
      dest: /home/ubuntu/ah-code-titans/start_ah.sh

  - name: run application in the background
    shell: |
      sudo systemctl daemon-reload
      sudo systemctl start keep_alive
      sudo systemctl enable keep_alive